### PR TITLE
Fix web UI

### PR DESCRIPTION
**Pull request by ClemensElflein**
When building the web UI with the current version of ionic, the popup is broken (grey overlay, but cannot select anything).

When changing the display type, the popup is functional, but not styled correctly. I'm not skilled enough with ionic to figure out why this is. It should look like this:

image

### CODE REVIEW

**Comment by maehw** [comment]
Hi Clemens.

Unfortunately, this doesn't build on my RPi:

```
pi@raspberrypi:~/self-o-mat/build $ cmake ..
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenCV: /usr (found version "4.6.0") 
-- Found Boost: /usr/lib/aarch64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0")  
-- Found Boost: /usr/lib/aarch64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0") found components: system thread filesystem chrono 
-- Found Cups: /usr/lib/aarch64-linux-gnu/libcups.so (found version "2.4.2") 
-- Found Protobuf: /usr/lib/aarch64-linux-gnu/libprotobuf.so (found version "3.21.12") 
-- No build type selected, default to Release
-- Found Python3: /usr/bin/python3 (found version "3.11.2") found components: Interpreter 
CMake Error at /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find asio (missing: ASIO_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  build/_deps/crow-src/cmake/Findasio.cmake:24 (find_package_handle_standard_args)
  build/_deps/crow-src/CMakeLists.txt:74 (find_package)
```

Some other (currently implicit?) dependency missing on my machine? (`asio` seems to be relevant)

```
pi@raspberrypi:~/self-o-mat $ git status
On branch fix/web-UI
Your branch is up to date with 'origin/fix/web-UI'.

nothing to commit, working tree clean
pi@raspberrypi:~/self-o-mat $ git log
commit 5cb804ba51f08b286b1d390da03418155a307dd4 (HEAD -> fix/web-UI, origin/fix/web-UI)
Author: Clemens Elflein <redacted>
Date:   Fri Dec 20 22:40:39 2024 +0100

    Fixed the web UI
```

**Comment by ClemensElflein** [comment]
Ah, yes you need to install `libasio-dev` packet using apt.

**Comment by maehw** [comment]
Good hint, thanks. I suggest we add that to the list of packet dependencies in README.md so that newcomers get a working setup.

Unfortunately, it still does not build on my RPi -- even though I did a `git clean -dffx` before building.

Cmake does not complain anymore, but `make` won't complete without errors. Does it require a specific asio version? Errors seem to originate from there.

```
...
[ 23%] Building CXX object CMakeFiles/self_o_mat.app.dir/src/main.cpp.o
In file included from /home/pi/self-o-mat/build/_deps/crow-src/include/crow.h:7,
                 from /home/pi/self-o-mat/src/api/BoothApi.h:10,
                 from /home/pi/self-o-mat/src/main.cpp:8:
/home/pi/self-o-mat/build/_deps/crow-src/include/crow/socket_adaptors.h:22: warning: "GET_IO_SERVICE" redefined
   22 | #define GET_IO_SERVICE(s) ((asio::io_context&)(s).get_executor().context())
      | 
...
In file included from /usr/include/asio/execution/detail/as_invocable.hpp:23,
                 from /usr/include/asio/execution/execute.hpp:20,
                 from /usr/include/asio/execution/executor.hpp:20,
                 from /usr/include/asio/associated_executor.hpp:22,
                 from /usr/include/asio.hpp:19,
                 from /home/pi/self-o-mat/build/_deps/crow-src/include/crow/socket_adaptors.h:13:
/usr/include/asio/execution/set_done.hpp:74:21: error: ‘template<class T, class> struct asio::traits::set_done_free’ conflicts with a previous declaration
   74 | using asio::traits::set_done_free;
      |                     ^~~~~~~~~~~~~
In file included from /usr/include/boost/asio/execution/set_done.hpp:21,
                 from /usr/include/boost/asio/execution/detail/as_invocable.hpp:23,
                 from /usr/include/boost/asio/execution/execute.hpp:20,
                 from /usr/include/boost/asio/execution/executor.hpp:20,
                 from /usr/include/boost/asio/associated_executor.hpp:20,
                 from /usr/include/boost/asio.hpp:21,
                 from /home/pi/self-o-mat/src/logic/BoothLogic.h:15:
/usr/include/boost/asio/traits/set_done_free.hpp:39:8: note: previous declaration ‘template<class T, class> struct boost::asio::traits::set_done_free’
   39 | struct set_done_free;
      |        ^~~~~~~~~~~~~
/usr/include/asio/execution/set_done.hpp:75:21: error: ‘template<class T, class> struct asio::traits::set_done_member’ conflicts with a previous declaration
   75 | using asio::traits::set_done_member;
      |                     ^~~~~~~~~~~~~~~
... (long list of errors)
```

Sorry, I'll need some more guidance here how to fix it (or try to).

**Comment by ClemensElflein** [comment]
I was able to reproduce this and I think it's due to conflicts between boost asio and standalone asio. For some reason it works on my system, but on the Pi it doesn't.

In the Crow issues I can find both statements "Crow doesn't work with boost anymore" and "it works". Latest release states it should be compatible in the change log, apparently it's not.

**Comment by ClemensElflein** [comment]
Note that the frontend change does not have anything to do with the backend change. So if you just need the booth working for now, we can just patch the frontend and solve this some other day.

**Comment by ClemensElflein** [comment]
Thinking about it, we should probably split this into three PRs:
1. Deboosting the project (with modern cpp and standalone asio there's really no reason to have boost)
2. Upgrading backend
3. (independent) fix frontend

**Comment by maehw** [comment]
Hi Clemens. Splitting the PR again sounds like a good idea.

I'd be happy with only the frontend being fixed because I did not have issued with the backend. Changes there sound more like "let's switch to some newer technology" - which is not strictly necessary to run the booth.

**Comment by ClemensElflein** [comment]
This PR should now only contain the updated frontend, hopefully it solves your issue!

**Comment by maehw** [comment]
Great, this fixes the web UI issues. The dropdown menus are visible again!

I also tested a few on/off switches. Seems to work! :)

Thank you very much!

**Pull request merged**
