### PR TITLE
Bugfix/build with newer boost and opencv libs

### LINKED ISSUE #17: Newer Boost library version will break the build of the self-o-mat software
@maehw ,
could you provide a PR to fix this?

Thanks!

### PR DESCRIPTION
**Pull request by maehw**
Fixes #17 

Apparently it was not also Boost but also OpenCV which caused me issues on my local machine.
I've finally cleaned up my fork and added new commits to a special bugfix branch.
Some additional log messages may have been kept in the changed files but could be removed if you want.

### CODE REVIEW

**Comment by ClemensElflein** [comment]
Hi @maehw,
thank you for the PR. The changes are good and I am able to compile the software using the instructions from the README file without problems now. We just need to remove the change in commit 4be17f3 since it will break the original self-o-mat boxes.

However we need to address this in another issue, since other errors are also related to app startup. I'll add an issue for this.

**Comment by ClemensElflein** [comment]
Could you add another commit reverting 4be17f3, then I'll merge the changes. Thank you!

**Comment by ClemensElflein** [comment]
I have added issue #22 for the startup file

**Comment by ClemensElflein** [comment]
BTW setting loading also does not work for me with the new boost version. I'll look into it.

**Review by ClemensElflein — APPROVED** [review]

**Comment by maehw** [comment]
Thank you for your quick response. I may have not tested the PR fully - I'll let you know if I also have issues regarding the loading of settings. Thanks for adding the new issue, too. Happy to help!

**Comment by ClemensElflein** [comment]
@maehw I have tested it again and serial comms are working as intended. Settings are getting loaded and I can trigger the photobooth. Can you confirm this?

**Comment by maehw** [comment]
Yes, I can confirm. Thanks for the fix! I can now even confirm that storing and re-loading the settings works. The web UI makes it really easy to change settings, well done Clemens!

**Comment by ClemensElflein** [comment]
Thank you! I'm glad to hear that it works now.

**Pull request merged**
